import type { ImageContent, Message, TextContent } from "@mariozechner/pi-ai";
import type { AgentMessage } from "@shiit/agent-core";

import { nanoid } from "@shiit/id";
import {
  appendFileSync,
  closeSync,
  existsSync,
  mkdirSync,
  openSync,
  readdirSync,
  readFileSync,
  readSync,
  statSync,
  writeFileSync,
} from "fs";
import { readdir, readFile, stat } from "fs/promises";
import { join, resolve } from "path";

import {
  getAgentDir as getDefaultAgentDir,
  getSessionsDir,
} from "../config.js";
import {
  createBranchSummaryMessage,
  createCompactionSummaryMessage,
  createCustomMessage,
  type CustomMessage,
} from "./messages.js";

export const CURRENT_SESSION_VERSION = 3;

export interface BranchSummaryEntry<T = unknown> extends SessionEntryBase {
  /** Extension-specific data (not sent to LLM) */
  details?: T;
  /** True if generated by an extension, false if pi-generated */
  fromHook?: boolean;
  fromId: string;
  summary: string;
  type: "branch_summary";
}

export interface CompactionEntry<T = unknown> extends SessionEntryBase {
  /** Extension-specific data (e.g., ArtifactIndex, version markers for structured compaction) */
  details?: T;
  firstKeptEntryId: string;
  /** True if generated by an extension, undefined/false if pi-generated (backward compatible) */
  fromHook?: boolean;
  summary: string;
  tokensBefore: number;
  type: "compaction";
}

/**
 * Custom entry for extensions to store extension-specific data in the session.
 * Use customType to identify your extension's entries.
 *
 * Purpose: Persist extension state across session reloads. On reload, extensions can
 * scan entries for their customType and reconstruct internal state.
 *
 * Does NOT participate in LLM context (ignored by buildSessionContext).
 * For injecting content into context, see CustomMessageEntry.
 */
export interface CustomEntry<T = unknown> extends SessionEntryBase {
  customType: string;
  data?: T;
  type: "custom";
}

/**
 * Custom message entry for extensions to inject messages into LLM context.
 * Use customType to identify your extension's entries.
 *
 * Unlike CustomEntry, this DOES participate in LLM context.
 * The content is converted to a user message in buildSessionContext().
 * Use details for extension-specific metadata (not sent to LLM).
 *
 * display controls TUI rendering:
 * - false: hidden entirely
 * - true: rendered with distinct styling (different from user messages)
 */
export interface CustomMessageEntry<T = unknown> extends SessionEntryBase {
  content: (ImageContent | TextContent)[] | string;
  customType: string;
  details?: T;
  display: boolean;
  type: "custom_message";
}

/** Raw file entry (includes header) */
export type FileEntry = SessionEntry | SessionHeader;

/** Label entry for user-defined bookmarks/markers on entries. */
export interface LabelEntry extends SessionEntryBase {
  label: string | undefined;
  targetId: string;
  type: "label";
}

export interface ModelChangeEntry extends SessionEntryBase {
  modelId: string;
  provider: string;
  type: "model_change";
}

export interface NewSessionOptions {
  id?: string;
  parentSession?: string;
}

export type ReadonlySessionManager = Pick<
  SessionManager,
  | "getBranch"
  | "getCwd"
  | "getEntries"
  | "getEntry"
  | "getHeader"
  | "getLabel"
  | "getLeafEntry"
  | "getLeafId"
  | "getSessionDir"
  | "getSessionFile"
  | "getSessionId"
  | "getSessionName"
  | "getTree"
>;

export interface SessionContext {
  messages: AgentMessage[];
  model: { modelId: string; provider: string } | null;
  thinkingLevel: string;
}

/** Session entry - has id/parentId for tree structure (returned by "read" methods in SessionManager) */
export type SessionEntry =
  | BranchSummaryEntry
  | CompactionEntry
  | CustomEntry
  | CustomMessageEntry
  | LabelEntry
  | ModelChangeEntry
  | SessionInfoEntry
  | SessionMessageEntry
  | ThinkingLevelChangeEntry;

export interface SessionEntryBase {
  id: string;
  parentId: null | string;
  timestamp: string;
  type: string;
}

export interface SessionHeader {
  cwd: string;
  id: string;
  parentSession?: string;
  timestamp: string;
  type: "session";
  version?: number; // v1 sessions don't have this
}

export interface SessionInfo {
  allMessagesText: string;
  created: Date;
  /** Working directory where the session was started. Empty string for old sessions. */
  cwd: string;
  firstMessage: string;
  id: string;
  messageCount: number;
  modified: Date;
  /** User-defined display name from session_info entries. */
  name?: string;
  /** Path to the parent session (if this session was forked). */
  parentSessionPath?: string;
  path: string;
}

/** Session metadata entry (e.g., user-defined display name). */
export interface SessionInfoEntry extends SessionEntryBase {
  name?: string;
  type: "session_info";
}

export type SessionListProgress = (loaded: number, total: number) => void;

export interface SessionMessageEntry extends SessionEntryBase {
  message: AgentMessage;
  type: "message";
}

/** Tree node for getTree() - defensive copy of session structure */
export interface SessionTreeNode {
  children: SessionTreeNode[];
  entry: SessionEntry;
  /** Resolved label for this entry, if any */
  label?: string;
  /** Timestamp of the latest label change for this entry, if any */
  labelTimestamp?: string;
}

export interface ThinkingLevelChangeEntry extends SessionEntryBase {
  thinkingLevel: string;
  type: "thinking_level_change";
}

/**
 * Manages conversation sessions as append-only trees stored in JSONL files.
 *
 * Each session entry has an id and parentId forming a tree structure. The "leaf"
 * pointer tracks the current position. Appending creates a child of the current leaf.
 * Branching moves the leaf to an earlier entry, allowing new branches without
 * modifying history.
 *
 * Use buildSessionContext() to get the resolved message list for the LLM, which
 * handles compaction summaries and follows the path from root to current leaf.
 */
export class SessionManager {
  private byId = new Map<string, SessionEntry>();
  private cwd: string;
  private fileEntries: FileEntry[] = [];
  private flushed = false;
  private labelsById = new Map<string, string>();
  private labelTimestampsById = new Map<string, string>();
  private leafId: null | string = null;
  private persist: boolean;
  private sessionDir: string;
  private sessionFile: string | undefined;
  private sessionId = "";

  private constructor(
    cwd: string,
    sessionDir: string,
    sessionFile: string | undefined,
    persist: boolean,
  ) {
    this.cwd = cwd;
    this.sessionDir = sessionDir;
    this.persist = persist;
    if (persist && sessionDir && !existsSync(sessionDir)) {
      mkdirSync(sessionDir, { recursive: true });
    }

    if (sessionFile) {
      this.setSessionFile(sessionFile);
    } else {
      this.newSession();
    }
  }

  /**
   * Continue the most recent session, or create new if none.
   * @param cwd Working directory
   * @param sessionDir Optional session directory. If omitted, uses default (~/.pi/agent/sessions/<encoded-cwd>/).
   */
  static continueRecent(cwd: string, sessionDir?: string): SessionManager {
    const dir = sessionDir ?? getDefaultSessionDir(cwd);
    const mostRecent = findMostRecentSession(dir);
    if (mostRecent) {
      return new SessionManager(cwd, dir, mostRecent, true);
    }
    return new SessionManager(cwd, dir, undefined, true);
  }

  /**
   * Create a new session.
   * @param cwd Working directory (stored in session header)
   * @param sessionDir Optional session directory. If omitted, uses default (~/.pi/agent/sessions/<encoded-cwd>/).
   */
  static create(cwd: string, sessionDir?: string): SessionManager {
    const dir = sessionDir ?? getDefaultSessionDir(cwd);
    return new SessionManager(cwd, dir, undefined, true);
  }

  /**
   * Fork a session from another project directory into the current project.
   * Creates a new session in the target cwd with the full history from the source session.
   * @param sourcePath Path to the source session file
   * @param targetCwd Target working directory (where the new session will be stored)
   * @param sessionDir Optional session directory. If omitted, uses default for targetCwd.
   */
  static forkFrom(
    sourcePath: string,
    targetCwd: string,
    sessionDir?: string,
  ): SessionManager {
    const sourceEntries = loadEntriesFromFile(sourcePath);
    if (sourceEntries.length === 0) {
      throw new Error(
        `Cannot fork: source session file is empty or invalid: ${sourcePath}`,
      );
    }

    const sourceHeader = sourceEntries.find((e) => e.type === "session") as
      | SessionHeader
      | undefined;
    if (!sourceHeader) {
      throw new Error(
        `Cannot fork: source session has no header: ${sourcePath}`,
      );
    }

    const dir = sessionDir ?? getDefaultSessionDir(targetCwd);
    if (!existsSync(dir)) {
      mkdirSync(dir, { recursive: true });
    }

    // Create new session file with new ID but forked content
    const newSessionId = nanoid();
    const timestamp = new Date().toISOString();
    const fileTimestamp = timestamp.replace(/[:.]/g, "-");
    const newSessionFile = join(dir, `${fileTimestamp}_${newSessionId}.jsonl`);

    // Write new header pointing to source as parent, with updated cwd
    const newHeader: SessionHeader = {
      cwd: targetCwd,
      id: newSessionId,
      parentSession: sourcePath,
      timestamp,
      type: "session",
      version: CURRENT_SESSION_VERSION,
    };
    appendFileSync(newSessionFile, `${JSON.stringify(newHeader)}\n`);

    // Copy all non-header entries from source
    for (const entry of sourceEntries) {
      if (entry.type !== "session") {
        appendFileSync(newSessionFile, `${JSON.stringify(entry)}\n`);
      }
    }

    return new SessionManager(targetCwd, dir, newSessionFile, true);
  }

  /** Create an in-memory session (no file persistence) */
  static inMemory(cwd: string = process.cwd()): SessionManager {
    return new SessionManager(cwd, "", undefined, false);
  }

  /**
   * List all sessions for a directory.
   * @param cwd Working directory (used to compute default session directory)
   * @param sessionDir Optional session directory. If omitted, uses default (~/.pi/agent/sessions/<encoded-cwd>/).
   * @param onProgress Optional callback for progress updates (loaded, total)
   */
  static async list(
    cwd: string,
    sessionDir?: string,
    onProgress?: SessionListProgress,
  ): Promise<SessionInfo[]> {
    const dir = sessionDir ?? getDefaultSessionDir(cwd);
    const sessions = await listSessionsFromDir(dir, onProgress);
    sessions.sort((a, b) => b.modified.getTime() - a.modified.getTime());
    return sessions;
  }

  /**
   * List all sessions across all project directories.
   * @param onProgress Optional callback for progress updates (loaded, total)
   */
  static async listAll(
    onProgress?: SessionListProgress,
  ): Promise<SessionInfo[]> {
    const sessionsDir = getSessionsDir();

    try {
      if (!existsSync(sessionsDir)) {
        return [];
      }
      const entries = await readdir(sessionsDir, { withFileTypes: true });
      const dirs = entries
        .filter((e) => e.isDirectory())
        .map((e) => join(sessionsDir, e.name));

      // Count total files first for accurate progress
      let totalFiles = 0;
      const dirFiles: string[][] = [];
      for (const dir of dirs) {
        try {
          const files = (await readdir(dir)).filter((f) =>
            f.endsWith(".jsonl"),
          );
          dirFiles.push(files.map((f) => join(dir, f)));
          totalFiles += files.length;
        } catch {
          dirFiles.push([]);
        }
      }

      // Process all files with progress tracking
      let loaded = 0;
      const sessions: SessionInfo[] = [];
      const allFiles = dirFiles.flat();

      const results = await Promise.all(
        allFiles.map(async (file) => {
          const info = await buildSessionInfo(file);
          loaded++;
          onProgress?.(loaded, totalFiles);
          return info;
        }),
      );

      for (const info of results) {
        if (info) {
          sessions.push(info);
        }
      }

      sessions.sort((a, b) => b.modified.getTime() - a.modified.getTime());
      return sessions;
    } catch {
      return [];
    }
  }

  /**
   * Open a specific session file.
   * @param path Path to session file
   * @param sessionDir Optional session directory for /new or /branch. If omitted, derives from file's parent.
   * @param cwdOverride Optional cwd override instead of the session header cwd.
   */
  static open(
    path: string,
    sessionDir?: string,
    cwdOverride?: string,
  ): SessionManager {
    // Extract cwd from session header if possible, otherwise use process.cwd()
    const entries = loadEntriesFromFile(path);
    const header = entries.find((e) => e.type === "session") as
      | SessionHeader
      | undefined;
    const cwd = cwdOverride ?? header?.cwd ?? process.cwd();
    // If no sessionDir provided, derive from file's parent directory
    const dir = sessionDir ?? resolve(path, "..");
    return new SessionManager(cwd, dir, path, true);
  }

  _persist(entry: SessionEntry): void {
    if (!this.persist || !this.sessionFile) return;

    const hasAssistant = this.fileEntries.some(
      (e) => e.type === "message" && e.message.role === "assistant",
    );
    if (!hasAssistant) {
      // Mark as not flushed so when assistant arrives, all entries get written
      this.flushed = false;
      return;
    }

    if (!this.flushed) {
      for (const e of this.fileEntries) {
        appendFileSync(this.sessionFile, `${JSON.stringify(e)}\n`);
      }
      this.flushed = true;
    } else {
      appendFileSync(this.sessionFile, `${JSON.stringify(entry)}\n`);
    }
  }

  /** Append a compaction summary as child of current leaf, then advance leaf. Returns entry id. */
  appendCompaction<T = unknown>(
    summary: string,
    firstKeptEntryId: string,
    tokensBefore: number,
    details?: T,
    fromHook?: boolean,
  ): string {
    const entry: CompactionEntry<T> = {
      details,
      firstKeptEntryId,
      fromHook,
      id: nanoid(),
      parentId: this.leafId,
      summary,
      timestamp: new Date().toISOString(),
      tokensBefore,
      type: "compaction",
    };
    this._appendEntry(entry);
    return entry.id;
  }

  /** Append a custom entry (for extensions) as child of current leaf, then advance leaf. Returns entry id. */
  appendCustomEntry(customType: string, data?: unknown): string {
    const entry: CustomEntry = {
      customType,
      data,
      id: nanoid(),
      parentId: this.leafId,
      timestamp: new Date().toISOString(),
      type: "custom",
    };
    this._appendEntry(entry);
    return entry.id;
  }

  /**
   * Append a custom message entry (for extensions) that participates in LLM context.
   * @param customType Extension identifier for filtering on reload
   * @param content Message content (string or TextContent/ImageContent array)
   * @param display Whether to show in TUI (true = styled display, false = hidden)
   * @param details Optional extension-specific metadata (not sent to LLM)
   * @returns Entry id
   */
  appendCustomMessageEntry<T = unknown>(
    customType: string,
    content: (ImageContent | TextContent)[] | string,
    display: boolean,
    details?: T,
  ): string {
    const entry: CustomMessageEntry<T> = {
      content,
      customType,
      details,
      display,
      id: nanoid(),
      parentId: this.leafId,
      timestamp: new Date().toISOString(),
      type: "custom_message",
    };
    this._appendEntry(entry);
    return entry.id;
  }

  /** Append a message as child of current leaf, then advance leaf. Returns entry id.
   * Does not allow writing CompactionSummaryMessage and BranchSummaryMessage directly.
   * Reason: we want these to be top-level entries in the session, not message session entries,
   * so it is easier to find them.
   * These need to be appended via appendCompaction() and appendBranchSummary() methods.
   */

  /**
   * Set or clear a label on an entry.
   * Labels are user-defined markers for bookmarking/navigation.
   * Pass undefined or empty string to clear the label.
   */
  appendLabelChange(targetId: string, label: string | undefined): string {
    if (!this.byId.has(targetId)) {
      throw new Error(`Entry ${targetId} not found`);
    }
    const entry: LabelEntry = {
      id: nanoid(),
      label,
      parentId: this.leafId,
      targetId,
      timestamp: new Date().toISOString(),
      type: "label",
    };
    this._appendEntry(entry);
    if (label) {
      this.labelsById.set(targetId, label);
      this.labelTimestampsById.set(targetId, entry.timestamp);
    } else {
      this.labelsById.delete(targetId);
      this.labelTimestampsById.delete(targetId);
    }
    return entry.id;
  }

  appendMessage(message: CustomMessage | Message, id?: string): string {
    const entryId = id ?? nanoid();
    const entry: SessionMessageEntry = {
      id: entryId,
      message,
      parentId: this.leafId,
      timestamp: new Date().toISOString(),
      type: "message",
    };
    this._appendEntry(entry);
    return entry.id;
  }

  /** Append a model change as child of current leaf, then advance leaf. Returns entry id. */
  appendModelChange(provider: string, modelId: string): string {
    const entry: ModelChangeEntry = {
      id: nanoid(),
      modelId,
      parentId: this.leafId,
      provider,
      timestamp: new Date().toISOString(),
      type: "model_change",
    };
    this._appendEntry(entry);
    return entry.id;
  }

  /** Append a session info entry (e.g., display name). Returns entry id. */
  appendSessionInfo(name: string): string {
    const entry: SessionInfoEntry = {
      id: nanoid(),
      name: name.trim(),
      parentId: this.leafId,
      timestamp: new Date().toISOString(),
      type: "session_info",
    };
    this._appendEntry(entry);
    return entry.id;
  }

  /** Append a thinking level change as child of current leaf, then advance leaf. Returns entry id. */
  appendThinkingLevelChange(thinkingLevel: string): string {
    const entry: ThinkingLevelChangeEntry = {
      id: nanoid(),
      parentId: this.leafId,
      thinkingLevel,
      timestamp: new Date().toISOString(),
      type: "thinking_level_change",
    };
    this._appendEntry(entry);
    return entry.id;
  }

  /**
   * Start a new branch from an earlier entry.
   * Moves the leaf pointer to the specified entry. The next appendXXX() call
   * will create a child of that entry, forming a new branch. Existing entries
   * are not modified or deleted.
   */
  branch(branchFromId: string): void {
    if (!this.byId.has(branchFromId)) {
      throw new Error(`Entry ${branchFromId} not found`);
    }
    this.leafId = branchFromId;
  }

  /**
   * Start a new branch with a summary of the abandoned path.
   * Same as branch(), but also appends a branch_summary entry that captures
   * context from the abandoned conversation path.
   */
  branchWithSummary(
    branchFromId: null | string,
    summary: string,
    details?: unknown,
    fromHook?: boolean,
  ): string {
    if (branchFromId !== null && !this.byId.has(branchFromId)) {
      throw new Error(`Entry ${branchFromId} not found`);
    }
    this.leafId = branchFromId;
    const entry: BranchSummaryEntry = {
      details,
      fromHook,
      fromId: branchFromId ?? "root",
      id: nanoid(),
      parentId: branchFromId,
      summary,
      timestamp: new Date().toISOString(),
      type: "branch_summary",
    };
    this._appendEntry(entry);
    return entry.id;
  }

  /**
   * Build the session context (what gets sent to the LLM).
   * Uses tree traversal from current leaf.
   */
  buildSessionContext(): SessionContext {
    return buildSessionContext(this.getEntries(), this.leafId, this.byId);
  }

  // =========================================================================
  // Tree Traversal
  // =========================================================================

  /**
   * Create a new session file containing only the path from root to the specified leaf.
   * Useful for extracting a single conversation path from a branched session.
   * Returns the new session file path, or undefined if not persisting.
   */
  createBranchedSession(leafId: string): string | undefined {
    const previousSessionFile = this.sessionFile;
    const path = this.getBranch(leafId);
    if (path.length === 0) {
      throw new Error(`Entry ${leafId} not found`);
    }

    // Filter out LabelEntry from path - we'll recreate them from the resolved map
    const pathWithoutLabels = path.filter((e) => e.type !== "label");

    const newSessionId = nanoid();
    const timestamp = new Date().toISOString();
    const fileTimestamp = timestamp.replace(/[:.]/g, "-");
    const newSessionFile = join(
      this.getSessionDir(),
      `${fileTimestamp}_${newSessionId}.jsonl`,
    );

    const header: SessionHeader = {
      cwd: this.cwd,
      id: newSessionId,
      parentSession: this.persist ? previousSessionFile : undefined,
      timestamp,
      type: "session",
      version: CURRENT_SESSION_VERSION,
    };

    // Collect labels for entries in the path
    const pathEntryIds = new Set(pathWithoutLabels.map((e) => e.id));
    const labelsToWrite: {
      label: string;
      targetId: string;
      timestamp: string;
    }[] = [];
    for (const [targetId, label] of this.labelsById) {
      if (pathEntryIds.has(targetId)) {
        labelsToWrite.push({
          label,
          targetId,
          timestamp: this.labelTimestampsById.get(targetId)!,
        });
      }
    }

    if (this.persist) {
      // Build label entries
      const lastEntryId =
        pathWithoutLabels[pathWithoutLabels.length - 1]?.id || null;
      let parentId = lastEntryId;
      const labelEntries: LabelEntry[] = [];
      for (const {
        label,
        targetId,
        timestamp: labelTimestamp,
      } of labelsToWrite) {
        const labelEntry: LabelEntry = {
          id: nanoid(),
          label,
          parentId,
          targetId,
          timestamp: labelTimestamp,
          type: "label",
        };
        pathEntryIds.add(labelEntry.id);
        labelEntries.push(labelEntry);
        parentId = labelEntry.id;
      }

      this.fileEntries = [header, ...pathWithoutLabels, ...labelEntries];
      this.sessionId = newSessionId;
      this.sessionFile = newSessionFile;
      this._buildIndex();

      // Only write the file now if it contains an assistant message.
      // Otherwise defer to _persist(), which creates the file on the
      // first assistant response, matching the newSession() contract
      // and avoiding the duplicate-header bug when _persist()'s
      // no-assistant guard later resets flushed to false.
      const hasAssistant = this.fileEntries.some(
        (e) => e.type === "message" && e.message.role === "assistant",
      );
      if (hasAssistant) {
        this._rewriteFile();
        this.flushed = true;
      } else {
        this.flushed = false;
      }

      return newSessionFile;
    }

    // In-memory mode: replace current session with the path + labels
    const labelEntries: LabelEntry[] = [];
    let parentId = pathWithoutLabels[pathWithoutLabels.length - 1]?.id || null;
    for (const {
      label,
      targetId,
      timestamp: labelTimestamp,
    } of labelsToWrite) {
      const labelEntry: LabelEntry = {
        id: nanoid(),
        label,
        parentId,
        targetId,
        timestamp: labelTimestamp,
        type: "label",
      };
      labelEntries.push(labelEntry);
      parentId = labelEntry.id;
    }
    this.fileEntries = [header, ...pathWithoutLabels, ...labelEntries];
    this.sessionId = newSessionId;
    this._buildIndex();
    return undefined;
  }

  /**
   * Delete a session file.
   * This requires SQLite persistence - base implementation throws.
   * Override in SqliteSessionManager for SQLite-backed deletion.
   */
  deleteSession(_sessionPath: string): void {
    throw new Error("deleteSession requires SQLite session manager");
  }

  /**
   * Walk from entry to root, returning all entries in path order.
   * Includes all entry types (messages, compaction, model changes, etc.).
   * Use buildSessionContext() to get the resolved messages for the LLM.
   */
  getBranch(fromId?: string): SessionEntry[] {
    const path: SessionEntry[] = [];
    const startId = fromId ?? this.leafId;
    let current = startId ? this.byId.get(startId) : undefined;
    while (current) {
      path.unshift(current);
      current = current.parentId ? this.byId.get(current.parentId) : undefined;
    }
    return path;
  }

  /**
   * Get all direct children of an entry.
   */
  getChildren(parentId: string): SessionEntry[] {
    const children: SessionEntry[] = [];
    for (const entry of this.byId.values()) {
      if (entry.parentId === parentId) {
        children.push(entry);
      }
    }
    return children;
  }

  getCwd(): string {
    return this.cwd;
  }

  /**
   * Get all session entries (excludes header). Returns a shallow copy.
   * The session is append-only: use appendXXX() to add entries, branch() to
   * change the leaf pointer. Entries cannot be modified or deleted.
   */
  getEntries(): SessionEntry[] {
    return this.fileEntries.filter(
      (e): e is SessionEntry => e.type !== "session",
    );
  }

  getEntry(id: string): SessionEntry | undefined {
    return this.byId.get(id);
  }

  /**
   * Get session header.
   */
  getHeader(): null | SessionHeader {
    const h = this.fileEntries.find((e) => e.type === "session");
    return h ? (h as SessionHeader) : null;
  }

  /**
   * Get the label for an entry, if any.
   */
  getLabel(id: string): string | undefined {
    return this.labelsById.get(id);
  }

  getLeafEntry(): SessionEntry | undefined {
    return this.leafId ? this.byId.get(this.leafId) : undefined;
  }

  getLeafId(): null | string {
    return this.leafId;
  }

  // =========================================================================
  // Branching
  // =========================================================================

  getSessionDir(): string {
    return this.sessionDir;
  }

  getSessionFile(): string | undefined {
    return this.sessionFile;
  }

  getSessionId(): string {
    return this.sessionId;
  }

  /** Get the current session name from the latest session_info entry, if any. */
  getSessionName(): string | undefined {
    // Walk entries in reverse to find the latest session_info entry.
    // Empty names explicitly clear the session title.
    const entries = this.getEntries();
    for (let i = entries.length - 1; i >= 0; i--) {
      const entry = entries[i];
      if (entry.type === "session_info") {
        return entry.name?.trim() || undefined;
      }
    }
    return undefined;
  }

  /**
   * Get the session as a tree structure. Returns a shallow defensive copy of all entries.
   * A well-formed session has exactly one root (first entry with parentId === null).
   * Orphaned entries (broken parent chain) are also returned as roots.
   */
  getTree(): SessionTreeNode[] {
    const entries = this.getEntries();
    const nodeMap = new Map<string, SessionTreeNode>();
    const roots: SessionTreeNode[] = [];

    // Create nodes with resolved labels
    for (const entry of entries) {
      const label = this.labelsById.get(entry.id);
      const labelTimestamp = this.labelTimestampsById.get(entry.id);
      nodeMap.set(entry.id, { children: [], entry, label, labelTimestamp });
    }

    // Build tree
    for (const entry of entries) {
      const node = nodeMap.get(entry.id)!;
      if (entry.parentId === null || entry.parentId === entry.id) {
        roots.push(node);
      } else {
        const parent = nodeMap.get(entry.parentId);
        if (parent) {
          parent.children.push(node);
        } else {
          // Orphan - treat as root
          roots.push(node);
        }
      }
    }

    // Sort children by timestamp (oldest first, newest at bottom)
    // Use iterative approach to avoid stack overflow on deep trees
    const stack: SessionTreeNode[] = [...roots];
    while (stack.length > 0) {
      const node = stack.pop()!;
      node.children.sort(
        (a, b) =>
          new Date(a.entry.timestamp).getTime() -
          new Date(b.entry.timestamp).getTime(),
      );
      stack.push(...node.children);
    }

    return roots;
  }

  isPersisted(): boolean {
    return this.persist;
  }

  /**
   * List sessions for this session manager's cwd and session directory.
   * Delegates to static list() for file-based session managers.
   * Override in SqliteSessionManager for SQLite-backed listing.
   */
  async list(
    cwd: string,
    sessionDir?: string,
    onProgress?: SessionListProgress,
  ): Promise<SessionInfo[]> {
    return SessionManager.list(cwd, sessionDir, onProgress);
  }

  newSession(options?: NewSessionOptions): string | undefined {
    this.sessionId = options?.id ?? nanoid();
    const timestamp = new Date().toISOString();
    const header: SessionHeader = {
      cwd: this.cwd,
      id: this.sessionId,
      parentSession: options?.parentSession,
      timestamp,
      type: "session",
      version: CURRENT_SESSION_VERSION,
    };
    this.fileEntries = [header];
    this.byId.clear();
    this.labelsById.clear();
    this.leafId = null;
    this.flushed = false;

    if (this.persist) {
      const fileTimestamp = timestamp.replace(/[:.]/g, "-");
      this.sessionFile = join(
        this.getSessionDir(),
        `${fileTimestamp}_${this.sessionId}.jsonl`,
      );
    }
    return this.sessionFile;
  }

  /**
   * Rename a session (adds session_info entry).
   * This requires SQLite persistence - base implementation throws.
   * Override in SqliteSessionManager for SQLite-backed renaming.
   */
  renameSession(_sessionFilePath: string, _nextName: string): void {
    throw new Error("renameSession requires SQLite session manager");
  }

  /**
   * Reset the leaf pointer to null (before any entries).
   * The next appendXXX() call will create a new root entry (parentId = null).
   * Use this when navigating to re-edit the first user message.
   */
  resetLeaf(): void {
    this.leafId = null;
  }

  /** Switch to a different session file (used for resume and branching) */
  setSessionFile(sessionFile: string): void {
    this.sessionFile = resolve(sessionFile);
    if (existsSync(this.sessionFile)) {
      this.fileEntries = loadEntriesFromFile(this.sessionFile);

      // If file was empty or corrupted (no valid header), truncate and start fresh
      // to avoid appending messages without a session header (which breaks the session)
      if (this.fileEntries.length === 0) {
        const explicitPath = this.sessionFile;
        this.newSession();
        this.sessionFile = explicitPath;
        this._rewriteFile();
        this.flushed = true;
        return;
      }

      const header = this.fileEntries.find((e) => e.type === "session") as
        | SessionHeader
        | undefined;
      this.sessionId = header?.id ?? nanoid();

      if (migrateToCurrentVersion(this.fileEntries)) {
        this._rewriteFile();
      }

      this._buildIndex();
      this.flushed = true;
    } else {
      const explicitPath = this.sessionFile;
      this.newSession();
      this.sessionFile = explicitPath; // preserve explicit path from --session flag
    }
  }

  private _appendEntry(entry: SessionEntry): void {
    this.fileEntries.push(entry);
    this.byId.set(entry.id, entry);
    this.leafId = entry.id;
    this._persist(entry);
  }

  private _buildIndex(): void {
    this.byId.clear();
    this.labelsById.clear();
    this.labelTimestampsById.clear();
    this.leafId = null;
    for (const entry of this.fileEntries) {
      if (entry.type === "session") continue;
      this.byId.set(entry.id, entry);
      this.leafId = entry.id;
      if (entry.type === "label") {
        if (entry.label) {
          this.labelsById.set(entry.targetId, entry.label);
          this.labelTimestampsById.set(entry.targetId, entry.timestamp);
        } else {
          this.labelsById.delete(entry.targetId);
          this.labelTimestampsById.delete(entry.targetId);
        }
      }
    }
  }

  private _rewriteFile(): void {
    if (!this.persist || !this.sessionFile) return;
    const content = `${this.fileEntries.map((e) => JSON.stringify(e)).join("\n")}\n`;
    writeFileSync(this.sessionFile, content);
  }
}

/**
 * Build the session context from entries using tree traversal.
 * If leafId is provided, walks from that entry to root.
 * Handles compaction and branch summaries along the path.
 */
export function buildSessionContext(
  entries: SessionEntry[],
  leafId?: null | string,
  byId?: Map<string, SessionEntry>,
): SessionContext {
  // Build uuid index if not available
  if (!byId) {
    byId = new Map<string, SessionEntry>();
    for (const entry of entries) {
      byId.set(entry.id, entry);
    }
  }

  // Find leaf
  let leaf: SessionEntry | undefined;
  if (leafId === null) {
    // Explicitly null - return no messages (navigated to before first entry)
    return { messages: [], model: null, thinkingLevel: "off" };
  }
  if (leafId) {
    leaf = byId.get(leafId);
  }
  if (!leaf) {
    // Fallback to last entry (when leafId is undefined)
    leaf = entries[entries.length - 1];
  }

  if (!leaf) {
    return { messages: [], model: null, thinkingLevel: "off" };
  }

  // Walk from leaf to root, collecting path
  const path: SessionEntry[] = [];
  let current: SessionEntry | undefined = leaf;
  while (current) {
    path.unshift(current);
    current = current.parentId ? byId.get(current.parentId) : undefined;
  }

  // Extract settings and find compaction
  let thinkingLevel = "off";
  let model: { modelId: string; provider: string } | null = null;
  let compaction: CompactionEntry | null = null;

  for (const entry of path) {
    if (entry.type === "thinking_level_change") {
      thinkingLevel = entry.thinkingLevel;
    } else if (entry.type === "model_change") {
      model = { modelId: entry.modelId, provider: entry.provider };
    } else if (entry.type === "message" && entry.message.role === "assistant") {
      model = {
        modelId: entry.message.model,
        provider: entry.message.provider,
      };
    } else if (entry.type === "compaction") {
      compaction = entry;
    }
  }

  // Build messages and collect corresponding entries
  // When there's a compaction, we need to:
  // 1. Emit summary first (entry = compaction)
  // 2. Emit kept messages (from firstKeptEntryId up to compaction)
  // 3. Emit messages after compaction
  const messages: AgentMessage[] = [];

  const appendMessage = (entry: SessionEntry) => {
    if (entry.type === "message") {
      messages.push(entry.message);
    } else if (entry.type === "custom_message") {
      messages.push(
        createCustomMessage(
          entry.customType,
          entry.content,
          entry.display,
          entry.details,
          entry.timestamp,
        ),
      );
    } else if (entry.type === "branch_summary" && entry.summary) {
      messages.push(
        createBranchSummaryMessage(
          entry.summary,
          entry.fromId,
          entry.timestamp,
        ),
      );
    }
  };

  if (compaction) {
    // Emit summary first
    messages.push(
      createCompactionSummaryMessage(
        compaction.summary,
        compaction.tokensBefore,
        compaction.timestamp,
      ),
    );

    // Find compaction index in path
    const compactionIdx = path.findIndex(
      (e) => e.type === "compaction" && e.id === compaction.id,
    );

    // Emit kept messages (before compaction, starting from firstKeptEntryId)
    let foundFirstKept = false;
    for (let i = 0; i < compactionIdx; i++) {
      const entry = path[i];
      if (entry.id === compaction.firstKeptEntryId) {
        foundFirstKept = true;
      }
      if (foundFirstKept) {
        appendMessage(entry);
      }
    }

    // Emit messages after compaction
    for (let i = compactionIdx + 1; i < path.length; i++) {
      const entry = path[i];
      appendMessage(entry);
    }
  } else {
    // No compaction - emit all messages, handle branch summaries and custom messages
    for (const entry of path) {
      appendMessage(entry);
    }
  }

  return { messages, model, thinkingLevel };
}

/** Exported for testing */
export function findMostRecentSession(sessionDir: string): null | string {
  try {
    const files = readdirSync(sessionDir)
      .filter((f) => f.endsWith(".jsonl"))
      .map((f) => join(sessionDir, f))
      .filter(isValidSessionFile)
      .map((path) => ({ mtime: statSync(path).mtime, path }))
      .sort((a, b) => b.mtime.getTime() - a.mtime.getTime());

    return files[0]?.path || null;
  } catch {
    return null;
  }
}

/**
 * Compute the default session directory for a cwd.
 * Encodes cwd into a safe directory name under ~/.pi/agent/sessions/.
 */
export function getDefaultSessionDir(
  cwd: string,
  agentDir: string = getDefaultAgentDir(),
): string {
  const safePath = `--${cwd.replace(/^[/\\]/, "").replace(/[/\\:]/g, "-")}--`;
  const sessionDir = join(agentDir, "sessions", safePath);
  if (!existsSync(sessionDir)) {
    mkdirSync(sessionDir, { recursive: true });
  }
  return sessionDir;
}

export function getLatestCompactionEntry(
  entries: SessionEntry[],
): CompactionEntry | null {
  for (let i = entries.length - 1; i >= 0; i--) {
    if (entries[i].type === "compaction") {
      return entries[i] as CompactionEntry;
    }
  }
  return null;
}

/** Exported for testing */
export function loadEntriesFromFile(filePath: string): FileEntry[] {
  if (!existsSync(filePath)) return [];

  const content = readFileSync(filePath, "utf8");
  const entries: FileEntry[] = [];
  const lines = content.trim().split("\n");

  for (const line of lines) {
    if (!line.trim()) continue;
    try {
      const entry = JSON.parse(line) as FileEntry;
      entries.push(entry);
    } catch {
      // Skip malformed lines
    }
  }

  // Validate session header
  if (entries.length === 0) return entries;
  const header = entries[0];
  if (header.type !== "session" || typeof (header as any).id !== "string") {
    return [];
  }

  return entries;
}

/** Exported for testing */
export function migrateSessionEntries(entries: FileEntry[]): void {
  migrateToCurrentVersion(entries);
}

/** Exported for compaction.test.ts */
export function parseSessionEntries(content: string): FileEntry[] {
  const entries: FileEntry[] = [];
  const lines = content.trim().split("\n");

  for (const line of lines) {
    if (!line.trim()) continue;
    try {
      const entry = JSON.parse(line) as FileEntry;
      entries.push(entry);
    } catch {
      // Skip malformed lines
    }
  }

  return entries;
}

async function buildSessionInfo(filePath: string): Promise<null | SessionInfo> {
  try {
    const content = await readFile(filePath, "utf8");
    const entries: FileEntry[] = [];
    const lines = content.trim().split("\n");

    for (const line of lines) {
      if (!line.trim()) continue;
      try {
        entries.push(JSON.parse(line) as FileEntry);
      } catch {
        // Skip malformed lines
      }
    }

    if (entries.length === 0) return null;
    const header = entries[0];
    if (header.type !== "session") return null;

    const stats = await stat(filePath);
    let messageCount = 0;
    let firstMessage = "";
    const allMessages: string[] = [];
    let name: string | undefined;

    for (const entry of entries) {
      // Extract session name (use latest, including explicit clears)
      if (entry.type === "session_info") {
        const infoEntry = entry as SessionInfoEntry;
        name = infoEntry.name?.trim() || undefined;
      }

      if (entry.type !== "message") continue;
      messageCount++;

      const message = (entry as SessionMessageEntry).message;
      if (!isMessageWithContent(message)) continue;
      if (message.role !== "user" && message.role !== "assistant") continue;

      const textContent = extractTextContent(message);
      if (!textContent) continue;

      allMessages.push(textContent);
      if (!firstMessage && message.role === "user") {
        firstMessage = textContent;
      }
    }

    const cwd =
      typeof (header as SessionHeader).cwd === "string"
        ? (header as SessionHeader).cwd
        : "";
    const parentSessionPath = (header as SessionHeader).parentSession;

    const modified = getSessionModifiedDate(
      entries,
      header as SessionHeader,
      stats.mtime,
    );

    return {
      allMessagesText: allMessages.join(" "),
      created: new Date((header as SessionHeader).timestamp),
      cwd,
      firstMessage: firstMessage || "(no messages)",
      id: (header as SessionHeader).id,
      messageCount,
      modified,
      name,
      parentSessionPath,
      path: filePath,
    };
  } catch {
    return null;
  }
}

function extractTextContent(message: Message): string {
  const content = message.content;
  if (typeof content === "string") {
    return content;
  }
  return content
    .filter((block): block is TextContent => block.type === "text")
    .map((block) => block.text)
    .join(" ");
}

function getLastActivityTime(entries: FileEntry[]): number | undefined {
  let lastActivityTime: number | undefined;

  for (const entry of entries) {
    if (entry.type !== "message") continue;

    const message = (entry as SessionMessageEntry).message;
    if (!isMessageWithContent(message)) continue;
    if (message.role !== "user" && message.role !== "assistant") continue;

    const msgTimestamp = (message as { timestamp?: number }).timestamp;
    if (typeof msgTimestamp === "number") {
      lastActivityTime = Math.max(lastActivityTime ?? 0, msgTimestamp);
      continue;
    }

    const entryTimestamp = (entry as SessionEntryBase).timestamp;
    if (typeof entryTimestamp === "string") {
      const t = new Date(entryTimestamp).getTime();
      if (!Number.isNaN(t)) {
        lastActivityTime = Math.max(lastActivityTime ?? 0, t);
      }
    }
  }

  return lastActivityTime;
}

function getSessionModifiedDate(
  entries: FileEntry[],
  header: SessionHeader,
  statsMtime: Date,
): Date {
  const lastActivityTime = getLastActivityTime(entries);
  if (typeof lastActivityTime === "number" && lastActivityTime > 0) {
    return new Date(lastActivityTime);
  }

  const headerTime =
    typeof header.timestamp === "string"
      ? new Date(header.timestamp).getTime()
      : NaN;
  return !Number.isNaN(headerTime) ? new Date(headerTime) : statsMtime;
}

function isMessageWithContent(message: AgentMessage): message is Message {
  return typeof (message as Message).role === "string" && "content" in message;
}

function isValidSessionFile(filePath: string): boolean {
  try {
    const fd = openSync(filePath, "r");
    const buffer = Buffer.alloc(512);
    const bytesRead = readSync(fd, new Uint8Array(buffer), 0, 512, 0);
    closeSync(fd);
    const firstLine = buffer.toString("utf8", 0, bytesRead).split("\n")[0];
    if (!firstLine) return false;
    const header = JSON.parse(firstLine);
    return header.type === "session" && typeof header.id === "string";
  } catch {
    return false;
  }
}

async function listSessionsFromDir(
  dir: string,
  onProgress?: SessionListProgress,
  progressOffset = 0,
  progressTotal?: number,
): Promise<SessionInfo[]> {
  const sessions: SessionInfo[] = [];
  if (!existsSync(dir)) {
    return sessions;
  }

  try {
    const dirEntries = await readdir(dir);
    const files = dirEntries
      .filter((f) => f.endsWith(".jsonl"))
      .map((f) => join(dir, f));
    const total = progressTotal ?? files.length;

    let loaded = 0;
    const results = await Promise.all(
      files.map(async (file) => {
        const info = await buildSessionInfo(file);
        loaded++;
        onProgress?.(progressOffset + loaded, total);
        return info;
      }),
    );
    for (const info of results) {
      if (info) {
        sessions.push(info);
      }
    }
  } catch {
    // Return empty list on error
  }

  return sessions;
}

/**
 * Run all necessary migrations to bring entries to current version.
 * Mutates entries in place. Returns true if any migration was applied.
 */
function migrateToCurrentVersion(entries: FileEntry[]): boolean {
  const header = entries.find((e) => e.type === "session") as
    | SessionHeader
    | undefined;
  const version = header?.version ?? 1;

  if (version >= CURRENT_SESSION_VERSION) return false;

  if (version < 2) migrateV1ToV2(entries);
  if (version < 3) migrateV2ToV3(entries);

  return true;
}

/** Migrate v1 → v2: add id/parentId tree structure. Mutates in place. */
function migrateV1ToV2(entries: FileEntry[]): void {
  const ids = new Set<string>();
  let prevId: null | string = null;

  for (const entry of entries) {
    if (entry.type === "session") {
      entry.version = 2;
      continue;
    }

    entry.id = nanoid();
    entry.parentId = prevId;
    prevId = entry.id;

    // Convert firstKeptEntryIndex to firstKeptEntryId for compaction
    if (entry.type === "compaction") {
      const comp = entry as { firstKeptEntryIndex?: number } & CompactionEntry;
      if (typeof comp.firstKeptEntryIndex === "number") {
        const targetEntry = entries[comp.firstKeptEntryIndex];
        if (targetEntry && targetEntry.type !== "session") {
          comp.firstKeptEntryId = targetEntry.id;
        }
        delete comp.firstKeptEntryIndex;
      }
    }
  }
}

/** Migrate v2 → v3: rename hookMessage role to custom. Mutates in place. */
function migrateV2ToV3(entries: FileEntry[]): void {
  for (const entry of entries) {
    if (entry.type === "session") {
      entry.version = 3;
      continue;
    }

    // Update message entries with hookMessage role
    if (entry.type === "message") {
      const msgEntry = entry as SessionMessageEntry;
      if (
        msgEntry.message &&
        (msgEntry.message as { role: string }).role === "hookMessage"
      ) {
        (msgEntry.message as { role: string }).role = "custom";
      }
    }
  }
}
